PRAGMA foreign_keys = OFF;
DELETE FROM payments;
DELETE FROM order_items;
DELETE FROM idempotency_keys;
DELETE FROM orders;
DELETE FROM cart_items;
DELETE FROM carts;
DELETE FROM contact_messages;
DELETE FROM sessions;
DELETE FROM addresses;
DELETE FROM product_specifications;
DELETE FROM variant_images;
DELETE FROM product_variants;
DELETE FROM product_images;
DELETE FROM products;
DELETE FROM categories;
DELETE FROM users;
DELETE FROM qa_states;
PRAGMA foreign_keys = ON;
